### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by Eorsion** [ptandeo/AnDA#5]
Hello, I am a student of Ocean University of China. I am studying ocean data fusion. I have the honor to read your paper and code, but I can't find the data set. I want to use it for scientific research. Could you send me the dataset? Thank you

**Comment by ptandeo** [comment]
Thank you for your interest in AnDA. The dataset used here are coming from toy models: Lorenz-63 and Lorenz-96. The code is generating those data. What is the issue when generating the Lorenz trajectories?

**Comment by Eorsion** [comment]
After your explanation, I have successfully deployed your code on the computer. Thank you very much for your reply.------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Pierre&amp;nbsp;Tandeo&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月4日(星期三) 下午4:06
收件人:&nbsp;&quot;ptandeo/AnDA&quot;<AnDA@noreply.github.com&gt;;
抄送:&nbsp;&quot;AnChen&quot;<1074045963@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ptandeo/AnDA] Dataset (#5)

**Comment by Eorsion** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
